name: Build ffmpeg-webrtc packages

on:
  release:
    types: [published, created]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential yasm nasm libx264-dev libssl-dev

      - name: Configure FFmpeg
        run: |
          ./configure --prefix=/opt/ffmpeg-webrtc --enable-muxer=whip --enable-openssl --enable-libx264 --enable-gpl --enable-nonfree --enable-shared

      - name: Build FFmpeg
        run: |
          make -j$(nproc)
          make install DESTDIR=$(pwd)/build

      - name: Create Debian package
        run: |
          mkdir -p build/DEBIAN
          echo "Package: ffmpeg-webrtc" > build/DEBIAN/control
          echo "Version: $(echo ${{ github.ref_name }} | sed 's/^v//')" >> build/DEBIAN/control
          echo "Architecture: amd64" >> build/DEBIAN/control
          echo "Maintainer: Your Name <your.email@example.com>" >> build/DEBIAN/control
          echo "Description: Custom FFmpeg build with WebRTC support" >> build/DEBIAN/control
          echo "Depends: libssl1.1, libx264-155" >> build/DEBIAN/control

          # Create symlinks in /usr/local/bin
          mkdir -p build/usr/local/bin
          ln -s /opt/ffmpeg-webrtc/bin/ffmpeg build/usr/local/bin/ffmpeg-webrtc
          ln -s /opt/ffmpeg-webrtc/bin/ffprobe build/usr/local/bin/ffprobe-webrtc

          dpkg-deb --build --root-owner-group -Zgzip build ffmpeg-webrtc.deb

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./ffmpeg-webrtc.deb
          asset_name: ffmpeg-webrtc-${{ github.ref_name }}.deb
          asset_content_type: application/vnd.debian.binary-package