name: Build ffmpeg-webrtc packages

on:
  release:
    types: [published, created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential yasm nasm libx264-dev libssl-dev

      - name: Configure FFmpeg
        run: |
          ./configure --enable-muxer=whip --enable-openssl --enable-libx264 --enable-gpl --enable-nonfree

      - name: Build FFmpeg
        run: |
          make -j$(nproc)

      - name: Create Debian package
        run: |
          mkdir -p debian/DEBIAN
          echo "Package: ffmpeg-webrtc" > debian/DEBIAN/control
          echo "Version: $(echo ${{ github.ref_name }} | sed 's/^v//')" >> debian/DEBIAN/control
          echo "Architecture: amd64" >> debian/DEBIAN/control
          echo "Maintainer: Your Name <your.email@example.com>" >> debian/DEBIAN/control
          echo "Description: Custom FFmpeg build with WebRTC support" >> debian/DEBIAN/control
          echo "Depends: libssl3, libx264-163" >> debian/DEBIAN/control
          mkdir -p debian/usr/local/bin
          cp ffmpeg debian/usr/local/bin/ffmpeg-webrtc
          cp ffprobe debian/usr/local/bin/ffprobe-webrtc
          dpkg-deb --build --root-owner-group -Zgzip debian ffmpeg-webrtc.deb

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./ffmpeg-webrtc.deb
          asset_name: ffmpeg-webrtc-${{ github.ref_name }}.deb
          asset_content_type: application/vnd.debian.binary-package