name: Build ffmpeg-webrtc packages

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential yasm nasm libx264-dev libssl-dev dpkg-dev

      - name: Configure FFmpeg
        run: |
          ./configure --prefix=/opt/ffmpeg-webrtc --enable-muxer=whip --enable-openssl --enable-libx264 --enable-gpl --enable-nonfree --enable-static --disable-shared

      - name: Build FFmpeg
        run: |
          make -j$(nproc)
          make install DESTDIR=$(pwd)/build

      - name: Prepare package
        run: |
          mkdir -p build/opt/ffmpeg-webrtc/lib
          cp /usr/lib/x86_64-linux-gnu/libx264.so.* build/opt/ffmpeg-webrtc/lib/
          cp /usr/lib/x86_64-linux-gnu/libssl.so.* build/opt/ffmpeg-webrtc/lib/
          cp /usr/lib/x86_64-linux-gnu/libcrypto.so.* build/opt/ffmpeg-webrtc/lib/

          # Create wrapper scripts
          mkdir -p build/opt/ffmpeg-webrtc/bin
          cat << EOF > build/opt/ffmpeg-webrtc/bin/ffmpeg-webrtc
          #!/bin/bash
          LD_LIBRARY_PATH=/opt/ffmpeg-webrtc/lib:\$LD_LIBRARY_PATH /opt/ffmpeg-webrtc/bin/ffmpeg "\$@"
          EOF
          cat << EOF > build/opt/ffmpeg-webrtc/bin/ffprobe-webrtc
          #!/bin/bash
          LD_LIBRARY_PATH=/opt/ffmpeg-webrtc/lib:\$LD_LIBRARY_PATH /opt/ffmpeg-webrtc/bin/ffprobe "\$@"
          EOF
          chmod +x build/opt/ffmpeg-webrtc/bin/ffmpeg-webrtc build/opt/ffmpeg-webrtc/bin/ffprobe-webrtc

          # Create DEBIAN directory and control file
          mkdir -p build/DEBIAN
          cat << EOF > build/DEBIAN/control
          Package: ffmpeg-webrtc
          Version: ${{ github.ref_name }}
          Section: video
          Priority: optional
          Architecture: amd64
          Maintainer: Your Name <your.email@example.com>
          Description: FFmpeg with WebRTC support
           This package contains a custom build of FFmpeg with WebRTC support.
          EOF

      - name: Build .deb package
        run: |
          dpkg-deb --build build ffmpeg-webrtc.deb

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./ffmpeg-webrtc.deb
          asset_name: ffmpeg-webrtc-${{ github.ref_name }}.deb
          asset_content_type: application/vnd.debian.binary-package