name: Build ffmpeg-webrtc packages

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read
  actions: read
  security-events: write

jobs:
  version:
    name: Generate release version
    uses: DigitalPath-Inc/.github-private/.github/workflows/semver-bump.yaml@master
    with:
      fail_on_error: false
  release:
    name: Create GitHub Release
    uses: DigitalPath-Inc/.github-private/.github/workflows/github-release.yaml@master
    needs:
      - version
    with:
      version: ${{ needs.version.outputs.version }}
    secrets:
      gh-app-id: ${{ secrets.GH_CROSS_REPO_APP_ID }}
      gh-app-key: ${{ secrets.GH_CROSS_REPO_KEY }}
  build:
    name: Build ffmpeg-webrtc package
    needs:
      - version
      - release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set version
        run: echo "VERSION=$(echo ${{ github.ref_name }} | sed 's/^[^0-9]*//')" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential yasm nasm libx264-dev libgnutls28-dev libsrt-gnutls-dev libvpx-dev

      - name: Configure FFmpeg
        run: |
          ./configure --prefix=/opt/ffmpeg-webrtc --enable-muxer=whip --enable-gnutls --enable-libx264 --enable-gpl --enable-nonfree --enable-static --disable-shared --enable-libsrt --enable-libvpx

      - name: Build FFmpeg
        run: |
          make -j$(nproc)

      - name: Prepare package
        run: |
          mkdir -p build/DEBIAN
          cat << EOF > build/DEBIAN/control
          Package: ffmpeg-webrtc
          Version: ${{ needs.version.outputs.version }}
          Architecture: amd64
          Maintainer: Your Name <your.email@example.com>
          Description: Custom FFmpeg build with WebRTC support
          EOF

          mkdir -p build/opt/ffmpeg-webrtc/bin
          cp ffmpeg build/opt/ffmpeg-webrtc/bin/ffmpeg
          cp ffprobe build/opt/ffmpeg-webrtc/bin/ffprobe

          mkdir -p build/usr/local/bin
          ln -s /opt/ffmpeg-webrtc/bin/ffmpeg build/usr/local/bin/ffmpeg-webrtc
          ln -s /opt/ffmpeg-webrtc/bin/ffprobe build/usr/local/bin/ffprobe-webrtc

      - name: Build .deb package
        run: |
          dpkg-deb --build build ffmpeg-webrtc.deb

      - name: Github App Token
        uses: actions/create-github-app-token@v3
        id: github-app-token
        with:
          app-id: ${{ secrets.GH_CROSS_REPO_APP_ID }}
          private-key: ${{ secrets.GH_CROSS_REPO_KEY }}
          owner: DigitalPath-Inc

      - name: Upload package to release
        run: gh release upload v${{ needs.version.outputs.version }} ffmpeg-webrtc.deb
        env:
          GH_TOKEN: ${{ steps.github-app-token.outputs.token }}

  
