name: Build ffmpeg-custom packages

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set version
        run: echo "VERSION=$(echo ${{ github.ref_name }} | sed 's/^[^0-9]*//')" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential yasm nasm libx264-dev libssl-dev dpkg-dev

      - name: Configure FFmpeg
        run: |
          ./configure --prefix=/usr/local --enable-muxer=whip --enable-openssl --enable-libx264 --enable-gpl --enable-nonfree --enable-static --disable-shared

      - name: Build FFmpeg
        run: |
          make -j$(nproc)

      - name: Prepare package
        run: |
          mkdir -p debian/DEBIAN
          echo "Package: ffmpeg-custom" > debian/DEBIAN/control
          echo "Version: ${{ env.VERSION }}" >> debian/DEBIAN/control
          echo "Architecture: amd64" >> debian/DEBIAN/control
          echo "Maintainer: Your Name <your.email@example.com>" >> debian/DEBIAN/control
          echo "Description: Custom FFmpeg build" >> debian/DEBIAN/control
          mkdir -p debian/usr/local/bin
          cp ffmpeg ffprobe debian/usr/local/bin/

      - name: Build .deb package
        run: |
          dpkg-deb --build debian ffmpeg-custom.deb

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./ffmpeg-custom.deb
          asset_name: ffmpeg-custom-${{ env.VERSION }}.deb
          asset_content_type: application/vnd.debian.binary-package