name: Build ffmpeg-webrtc packages

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set version
        run: echo "VERSION=$(echo ${{ github.ref_name }} | sed 's/^[^0-9]*//')" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential yasm nasm libx264-dev libssl-dev dpkg-dev

      - name: Configure FFmpeg
        run: |
          ./configure --prefix=/opt/ffmpeg-webrtc --enable-muxer=whip --enable-openssl --enable-libx264 --enable-gpl --enable-nonfree --enable-static --disable-shared

      - name: Build FFmpeg
        run: |
          make -j$(nproc)

      - name: Prepare package
        run: |
          mkdir -p debian/DEBIAN
          cat << EOF > debian/DEBIAN/control
          Package: ffmpeg-webrtc
          Version: ${{ env.VERSION }}
          Architecture: amd64
          Maintainer: Your Name <your.email@example.com>
          Description: Custom FFmpeg build with WebRTC support
          EOF

          mkdir -p debian/opt/ffmpeg-webrtc/bin
          cp ffmpeg debian/opt/ffmpeg-webrtc/bin/ffmpeg
          cp ffprobe debian/opt/ffmpeg-webrtc/bin/ffprobe

          mkdir -p debian/usr/local/bin
          cat << EOF > debian/usr/local/bin/ffmpeg-webrtc
          #!/bin/bash
          /opt/ffmpeg-webrtc/bin/ffmpeg "\$@"
          EOF
          cat << EOF > debian/usr/local/bin/ffprobe-webrtc
          #!/bin/bash
          /opt/ffmpeg-webrtc/bin/ffprobe "\$@"
          EOF
          chmod +x debian/usr/local/bin/ffmpeg-webrtc debian/usr/local/bin/ffprobe-webrtc

      - name: Build .deb package
        run: |
          dpkg-deb --build debian ffmpeg-webrtc.deb

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./ffmpeg-webrtc.deb
          asset_name: ffmpeg-webrtc-${{ env.VERSION }}.deb
          asset_content_type: application/vnd.debian.binary-package